assignment/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('post.urls', namespace='post') ),
]

assignment/post/urls.py
from django.urls import path
from .views import home, createAccount, detailAccount, listAccount, updateAccount, deleteAccount, createStock, detailStock, listStock, updateStock, deleteStock

app_name = 'post'

urlpatterns = [
    path('',listStock, name='main'),
    path('account/create/',createAccount,name='createAcc'),
    path('account/detail/<int:pk>/',detailAccount,name='detailAcc'),
    path('account/list/',listAccount,name='listAcc'),
    path('account/detail/<int:pk>/update/',updateAccount,name='updateAcc'),
    path('account/detail/<int:pk>/delete/',deleteAccount,name='deleteAcc'),
    path('stock/create/', createStock, name='createSto'),
    path('stock/detail/<int:pk>/', detailStock, name='detailSto'),
    path('stock/list/', listStock, name='listSto'),
    path('stock/detail/<int:pk>/update/', updateStock, name='updateSto'),
    path('stock/detail/<int:pk>/delete/', deleteStock, name='deleteSto'),
]

assignment/post/models.py
from django.db import models
from django.urls import reverse


class Account(models.Model):
    name = models.CharField(max_length=100)
    call = models.CharField(max_length=100)
    address = models.CharField(max_length=100)

    def get_absolute_url(self):
        return reverse('post:detailAcc',kwargs={'pk':self.pk})

    def __str__(self):
        return '{}, {}, {}'.format(self.name, self.call, self.address)


class Stock(models.Model):
    title=models.CharField(max_length=100)
    image = models.ImageField(blank=True, null=True)
    content = models.TextField(blank=True)
    price = models.CharField(max_length=100)
    amount = models.CharField(max_length=100)

    def __str__(self):
        return '{}/ 가격: {}/ 남은 수량: {}'.format(self.title, self.price, self.amount)

assignment/post/views.py
import logging
from django.shortcuts import render, redirect, reverse
from .models import Stock,Account
# Create your views here.

def home(request) :
    return render(request,'post/list_stock.html')

def createAccount(request) :
    if request.method == "GET":
        return render(request,'post/create_account.html',context={})

    name=request.POST['name']
    call=request.POST['call']
    address=request.POST['address']
    account=Account.objects.create(name=name, call=call, address=address)
    pk=account.id
    url = reverse('post:detailAcc', kwargs={'pk':pk})
    return redirect(to=url)

def detailAccount(request, pk):
    account = Account.objects.get(id=pk)
    context = {
        'account' : account
    }
    return render(request,'post/detail_account.html',context=context)

def listAccount(request):
    queryset = Account.objects.all()
    context = {
        'accounts' : queryset,
    }
    return render(request,'post/list_account.html',context=context)

def deleteAccount(request,pk):
    account=Account.objects.get(id=pk)
    account.delete()

    url = reverse('post:listAcc')
    return redirect(to=url)

def updateAccount(request, pk):
    account=Account.objects.get(id=pk)

    if request.method =='GET':
        context = {
            'account':account
        }
        return render(request,'post/update_account.html',context=context)

    name=request.POST['name']
    call=request.POST['call']
    address=request.POST['address']
    #DB에 바꿀 내용들
    account.name=name
    account.call=call
    account.address=address
    account.save()

    url = reverse('post:detailAcc', kwargs={'pk': pk})
    return redirect(to=url)


def createStock(request) :
    if request.method == "GET":
        return render(request,'post/create_stock.html',context={})

    title=request.POST['title']
    image=request.POST['image']
    content=request.POST['content']
    price = request.POST['price']
    amount = request.POST['amount']
    stock=Stock.objects.create(title=title, image=image, content=content, price=price, amount=amount)
    pk=stock.id
    url = reverse('post:detailSto', kwargs={'pk':pk})
    return redirect(to=url)

def detailStock(request, pk):
    stock = Stock.objects.get(id=pk)
    context = {
        'stock' : stock
    }
    return render(request,'post/detail_stock.html',context=context)

def listStock(request):
    queryset = Stock.objects.all()
    context = {
        'stocks' : queryset,
    }
    return render(request,'post/list_stock.html',context=context)

def deleteStock(request,pk):
    stock=Stock.objects.get(id=pk)
    stock.delete()

    url = reverse('post:listSto')
    return redirect(to=url)

def updateStock(request, pk):
    stock=Stock.objects.get(id=pk)

    if request.method =='GET':
        context = {
            'stock':stock
        }
        return render(request,'post/update_stock.html',context=context)

    title=request.POST['title']
    image=request.POST['image']
    content=request.POST['content']
    price = request.POST['price']
    amount = request.POST['amount']
    #DB에 바꿀 내용들
    stock.title=title
    stock.image=image
    stock.content=content
    stock.price=price
    stock.amount=amount
    stock.save()

    url = reverse('post:detailSto', kwargs={'pk': pk})
    return redirect(to=url)

assignment/config/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Title</title>
<style>
    * {
        margin: 0;
        padding: 0;
    }

    ul {
        list-style:none;
        margin:0;
        padding:0;
    }

    li {
        margin: 0 0 0 0;
        padding: 0 0 0 0;
        border : 0;
        float: left;
    }

    a {
        text-decoration: none;
    }

    .nav {
        display: block;
        background-color: rgba(40, 58, 90, 1);
        width: 100%;
        position: fixed;

    }
    .nav .nav__navbar {
        display: flex;
        justify-content: space-evenly;
        text-align: center;
        height: 40px;
        padding: 15px 0;
        align-items: center;
    }

    .nav__column {
        color: white;
    }

    .nav__column .nav__list {
        display: flex;
        text-align: center;

    }

    .nav__column .mainIcon > a{
        color : cadetblue;
    }

    .nav__list .nav__item > a{
        color: white;
    }

    .nav__list .nav__item {

        padding-left: 15px;
    }

    .main{
        display: block;
        padding-top: 70px;
    }

    .footer{
        display: block;
    }




</style>
</head>
<body>
<div class="nav">
<div class="nav__navbar">
    <div class="nav__column">
        <p class="mainIcon"><a href="{% url "post:listSto" %}" target="_self">Inventory Manage</a></p>
    </div>
    <div class="nav__column">
        <ul class="nav__list">
            <li class="nav__item"><a href="{% url "post:createSto" %}" target="_self">상품 등록</a></li>
            <li class="nav__item"><a href="{% url "post:createAcc" %}" target="_self">거래처 등록</a></li>
            <li class="nav__item"><a href="{% url "post:listAcc" %}" target="_self">거래처 관리</a></li>
        </ul>
    </div>

</div>
</div>
<div class="main">
    {% block content %}
    {% endblock %}
</div>

<div class="footer">
    <hr/>
    <h4>아무내용이나적는footer</h4>
    <h5>나도 한줄 길게 아무내용이나 더 적어보자 띠링띠링</h5>
</div>


</body>
</html>

assignment/post/templates/post/create_account.html
{% extends "layout.html" %}
{% block content %}
    <h2>Account Register</h2>

    <form action='{% url 'post:createAcc' %}' method='POST'>
        {% csrf_token %}
        Name:
        <input type="text" name="name" /><br/>
        Call:
        <input type="text" name="call" /><br/>
        Address:
        <input type="text" name="address" /><br/>
        <input type="submit" value="저장"/>
    </form>
{% endblock %}

assignment/post/templates/post/create_stock.html
{% extends "layout.html" %}
{% block content %}
    <h2>Item Register</h2>

    <form action='{% url 'post:createSto' %}' method='POST'>
        {% csrf_token %}
        Title:
        <input type="text" name="title" /><br/>
        Image:
        <input type="image" name="image" /><br/>
        Content:
        <textarea name="content"></textarea><br/>
        Price:
        <input type="text" name="price" /><br/>
        Amount:
        <input type="text" name="amount" /><br/><br/>
        <input type="submit" value="저장"/>
    </form>
{% endblock %}

assignment/post/templates/post/detail_account.html
{% extends "layout.html" %}

{% block content %}
    <h2>{{ account.name }}</h2>

    {{ account.call }}<br/>
    {{ account.address }}<br/>
    <hr/>
    <a href="{% url "post:listAcc" %}">목록</a><br/>
    <a href="{% url "post:updateAcc" pk=account.pk %}">수정</a><br/>
    <a href="{% url "post:deleteAcc" pk=account.pk %}">삭제</a><br/>
{% endblock %}

assignment/post/templates/post/detail_stock.html
{% extends "layout.html" %}

{% block content %}
    <h2>{{ stock.title }}</h2>

    {{ stock.content }}<br/>
    {{ stock.price }}<br/>
    {{ stock.amount }}<br/>

    <hr/>
    <a href="{% url "post:listSto" %}">목록</a><br/>
    <a href="{% url "post:updateSto" pk=account.pk %}">수정</a><br/>
    <a href="{% url "post:deleteSto" pk=account.pk %}">삭제</a><br/>
{% endblock %}

assignment/post/templates/post/list_account.html
{% extends "layout.html" %}

{% block content %}
<ul>
    {% for account in accounts %}
        <li><a href="{% url 'post:detailAcc' pk=account.pk %}">{{ account }}</a></li><br/>
    {% endfor %}
</ul>
{% endblock %}

assignment/post/templates/post/list_stock.html
{% extends "layout.html" %}

{% block content %}
<ul>
    {% for stock in stocks %}
        <li><a href="{% url 'post:detailSto' pk=stock.pk %}">{{ stock }}</a></li><br/>
    {% endfor %}
</ul>
{% endblock %}

assignment/post/templates/post/update_account.html
{% extends "layout.html" %}
{% block content %}
    <h2>Account 수정하기</h2>

    <form action='{% url 'post:createAcc' %}' method='POST'>
        {% csrf_token %}
        Name:
        <input type="text" name="name" value={{ account.name }}><br/>
        Call:
        <input type="text" name="call" value={{ account.call }}><br/>
        Address:
        <input type="text" name="address" value={{ account.address }}><br/>
        <input type="submit" value="저장"/>
    </form>
{% endblock %}

assignment/post/templates/post/update_stock.html
{% extends "layout.html" %}
{% block content %}
    <h2>Item 수정하기</h2>

    <form action='{% url 'post:createSto' %}' method='POST'>
        {% csrf_token %}
        Title:
        <input type="text" name="title" value={{ stock.title }}><br/>
        Image:
        <input type="image" name="image" value={{ stock.image }}><br/>
        Content:
        <textarea name="content" >{{ stock.content }}</textarea><br/>
        Price:
        <input type="text" name="price" value={{ stock.price }}><br/>
        Amount:
        <input type="text" name="amount" value={{ stock.amount }}><br/><br/>
        <input type="submit" value="저장"/>
    </form>
{% endblock %}